feat: add `rules_download@1.0.0-alpha.7`
bazelbuild/bazel-central-registry pull request #1367
Opened 2024-01-23 13:26 UTC by mattyclarkson

This module implements repository rules that are helpful for downloading remote resources hermetically.

It currently has three repository rules for use in `MODULE.bazel`:

- `download_file`: download a single file
- `download_archive`: download a optionally compressed archive/tarball
- `download_deb`: download a debian package and unpack the contained data tarball

The rules add two novel things:

- Allow setting up (sym|hard)links after the artifact has been downloaded
- Run hermetic commands provided via `tools` and using `$(location )` replacement

Running for post download hermetic commands is a cruicial feature to make sure we depend on nothing in the host.

See the [readme](https://gitlab.arm.com/bazel/rules_download#getting-started) for example usage.

2024-01-23 13:26 UTC, mattyclarkson commented
@Wyverald this module likely has the same naming issue as #1270. We may want to change the name to `download_utils`?

2024-01-23 19:37 UTC, Wyverald commented on modules/rules_download/metadata.json
> +    "homepage": "https://gitlab.arm.com/bazel/rules_download",
could you please add yourself as a maintainer here?

```
"maintainer": [
  { "github": "mattyclarkson", "email": "...", "name": "..." }
]
```

2024-01-23 19:38 UTC, Wyverald commented
> @Wyverald this module likely has the same naming issue as #1270. We may want to change the name to `download_utils`?

I don't really have a good idea for this particular module. Perhaps others could chime in?

2024-02-12 16:54 UTC, bazel-io commented
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (rules_download) have been updated in this PR. Please review the changes.

2024-02-13 09:17 UTC, meteorcloudy commented
Yeah, I also slightly prefer `download_utils`.

2024-02-13 12:23 UTC, mattyclarkson commented
> Yeah, I also slightly prefer `download_utils`.

Good with me. Let me respin on our end and get a beta out.

2024-02-14 10:58 UTC, bazel-io commented
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (download_utils) have been updated in this PR. Please review the changes.

2024-02-14 11:01 UTC, meteorcloudy requested changes

2024-02-14 11:32 UTC, mattyclarkson commented on modules/download_utils/1.0.0-beta.1/presubmit.yml
> +      # - macos
I left the comment in the commit, I can add it in the file also if that is preferred. I can reenable `macos-amd64` now.

2024-02-14 11:45 UTC, mattyclarkson commented on modules/download_utils/1.0.0-beta.1/presubmit.yml
> +      # - macos
I've reenabled MacOS Amd64.

Windows is still disabled until I can figure out why the BuildKite Windows CI does not validate the SSL certificate for `gitlab.arm.com`.

2024-02-14 12:23 UTC, meteorcloudy commented on modules/download_utils/1.0.0-beta.1/presubmit.yml
> +      # - macos
I see, thanks!

2024-02-14 12:24 UTC, meteorcloudy approved these changes

2024-02-14 12:24 UTC, merged