Support `pure = "on"` for `circl@1.3.7`
bazelbuild/bazel-central-registry pull request #1629
Opened 2024-03-15 16:51 UTC by mattyclarkson

This switches out `purego` build tags for the inverse `!cgo` build tags.

The correct files are then conditionally added and compiled.

This supports `pure = "on"` binaries.

A patch adds a `pure = "on"` unit test to prrevent regressions.

2024-03-15 16:52 UTC, bazel-io commented
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (circl) have been updated in this PR. Please review the changes.

2024-03-15 16:52 UTC, mattyclarkson commented
RFC: @fmeum

2024-03-18 10:26 UTC, meteorcloudy requested changes

2024-03-18 10:26 UTC, meteorcloudy commented on modules/circl/1.3.7.bcr.1/MODULE.bazel
> +    version = "1.3.7",
This has to be `1.3.7.bcr.1`

2024-03-18 10:50 UTC, mattyclarkson commented on modules/circl/1.3.7.bcr.1/patches/switch_purego_build_tag_to_cgo.patch
@fmeum my question here would be: is switching to `!cgo` the correct thing or should `rules_go` be setting the `purego` build tag when `pure = "on"`?

2024-03-18 11:03 UTC, mattyclarkson commented on modules/circl/1.3.7.bcr.1/patches/switch_purego_build_tag_to_cgo.patch
Seems that `purego` is the community accepted flag: golang/go/#23172

Should we drop this and add `purego` build flag to `rules_go`?

2024-03-18 11:39 UTC, mattyclarkson commented on modules/circl/1.3.7.bcr.1/patches/switch_purego_build_tag_to_cgo.patch
This patch mirrors [this comment](https://github.com/golang/go/issues/23172#issuecomment-2000390548) in that `cgo` is basically `!purego`.

2024-03-20 09:30 UTC, fmeum commented on modules/circl/1.3.7.bcr.1/patches/switch_purego_build_tag_to_cgo.patch
Based on the Go thread you linked, I would prefer to add `purego` support to rules_go instead of moving this module further away from upstream.

Does that sound reasonable to you? Let me know if you want help with the change to rules_go.

2024-03-22 09:33 UTC, mattyclarkson commented on modules/circl/1.3.7.bcr.1/patches/switch_purego_build_tag_to_cgo.patch
> Does that sound reasonable to you?

Yeah. That's a better, more general solution assuming that the community aligns on `purego`. We can always upstream `purego` tags to projects or patch them in the BCR. I'll get on that patch now

---

Any views on the `noasm` flag? Seems that various projects use that to control adding `.S` files in but I'm unsure what that means for `rules_go`? If `rules_go` also specified `noasm` when `pure = "on"` then the `gazelle` generation for `circl` would likely "Just Work :tm:"

Personally, I don't really understand the intersection between `cgo`, `purego` and `noasm`. To myself, they seem mutually exclusive. If `purego` is on, surely that means `!cgo`? Also, if you want `purego`, surely that means `noasm` as well?

2024-03-22 09:39 UTC, mattyclarkson commented on modules/circl/1.3.7.bcr.1/patches/switch_purego_build_tag_to_cgo.patch
For example, the `go` developers do not include assembly when `purego` is on: https://go-review.googlesource.com/c/go/+/561935

`circl` has a separate `noasm` and `purego` tag.

2024-03-22 09:46 UTC, mattyclarkson commented on modules/circl/1.3.7.bcr.1/patches/switch_purego_build_tag_to_cgo.patch
Have raised cloudflare/circl#491 for upstream discussion.

2024-03-26 13:37 UTC, mattyclarkson commented on modules/circl/1.3.7.bcr.1/patches/switch_purego_build_tag_to_cgo.patch
cloudflare/circl#492 aligns on `purego`.

2024-05-08 19:47 UTC, mattyclarkson commented
cloudflare/circl#492 is in `1.3.8`
bazelbuild/bazel-gazelle#1767 understands the `purego` tag which is in `0.36.0`
bazelbuild/rules_go#3901 sets the `purego` tag when `pure = "on"`.

Once `rules_go` gets a release. We won't need a `circl` BCR module because Gazelle will automatically create the correct `BUILD.bazel` files for `cloudflare/circl`.

Closing this.

2024-05-08 19:47 UTC, closed without merging

2024-05-09 07:34 UTC, fmeum commented
@mattyclarkson Wouldn't the module still be needed for the CGO version of circl? Have you observed a difference in performance?

2024-05-09 08:15 UTC, mattyclarkson commented
The CGO version will be compiled if `pure = "off"` (or not specified). i.e. if the `purego` tag is not provided to the `circl` build then it will compile in all the assembly.

2024-05-09 08:22 UTC, fmeum commented
Sure, but does gazelle generate the correct build files for it to find the assembly without a patch? That's what I introduced the module for in the first place.

2024-05-09 08:41 UTC, mattyclarkson commented
You are correct, sorry. It doesn't correctly find the header file. We will still need a patch. I was only testing with `pure = "on"` 🙄

I'll get one up once the `purego` friendly `rules_go` is released.

2024-05-09 09:50 UTC, mattyclarkson commented
@fmeum I've opened #1986. GitHub wasn't letting me reopen this one 🤷