tclap@1.2.5
bazelbuild/bazel-central-registry pull request #1646
Opened 2024-03-18 07:18 UTC by mmorel-35

Release: https://github.com/mirror/tclap/releases/tag/v1.2.5

2024-03-18 07:19 UTC, bazel-io commented
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (tclap) have been updated in this PR. Please review the changes.

2024-03-19 10:51 UTC, meteorcloudy requested changes

2024-03-19 10:51 UTC, meteorcloudy commented on modules/tclap/1.2.5/MODULE.bazel
> +    repo_name = "com_github_mirror_tclap"
Why do we need `repo_name = "com_github_mirror_tclap"`

2024-03-20 10:13 UTC, meteorcloudy submitted a review, later dismissed
Thanks!

2024-03-20 10:14 UTC, meteorcloudy commented on modules/tclap/metadata.json
> +            "github": "DAarno",
Wait, will @DAarno actually help maintain this module? This should be the module maintainer for BCR, it doesn't have to be the maintainer of the original project.

2024-03-20 13:06 UTC, meteorcloudy approved these changes

2024-03-20 13:06 UTC, merged