opentracing-cpp@1.6.0
bazelbuild/bazel-central-registry pull request #1656
Opened 2024-03-20 17:58 UTC by mmorel-35

Release: https://github.com/opentracing/opentracing-cpp/releases/tag/v1.6.0

2024-03-20 17:59 UTC, bazel-io commented
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (io_opentracing_cpp, opentracing-cpp) have been updated in this PR. Please review the changes.

2024-03-21 09:58 UTC, meteorcloudy submitted a review, later dismissed

2024-03-21 10:01 UTC, meteorcloudy requested changes

2024-03-21 10:01 UTC, meteorcloudy commented on modules/opentracing-cpp/1.6.0/presubmit.yml
> +verify_linux_targets:
The syntax is wrong, all jobs must be under `tasks:`,

Check https://github.com/bazelbuild/continuous-integration/tree/master/buildkite#basic-syntax

2024-03-21 12:42 UTC, meteorcloudy requested changes

2024-03-21 12:42 UTC, meteorcloudy commented on modules/opentracing-cpp/1.6.0/presubmit.yml
> +    - '@io_opentracing_cpp//...'
`io_opentracing_cpp` should be `opentracing_cpp`

2024-03-22 09:53 UTC, meteorcloudy approved these changes

2024-03-22 09:54 UTC, merged