Add argparse 3.0
bazelbuild/bazel-central-registry pull request #1801
Opened 2024-04-10 16:31 UTC by TendTo

Adding the lightweight header only library [argparse](https://github.com/p-ranav/argparse) to the BCR

2024-04-10 16:31 UTC, bazel-io commented
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (argparse) have been updated in this PR. Please review the changes.

2024-04-11 10:09 UTC, meteorcloudy requested changes

2024-04-11 10:09 UTC, meteorcloudy commented on modules/argparse/metadata.json
> +    "maintainers": [],
Do you mind adding yourself as a maintainer for this module?

2024-04-11 11:53 UTC, meteorcloudy approved these changes

2024-04-11 11:55 UTC, merged