highwayhash@0.0.0-20240305-5ad3bf8
bazelbuild/bazel-central-registry pull request #1817
Opened 2024-04-13 08:30 UTC by mmorel-35

https://github.com/google/highwayhash/tree/5ad3bf8444cfc663b11bf367baaa31f36e7ff7c8

Used by:
* https://github.com/google/riegeli

2024-04-13 08:31 UTC, bazel-io commented
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (highwayhash) have been updated in this PR. Please review the changes.

2024-04-15 08:57 UTC, meteorcloudy requested changes

2024-04-15 10:06 UTC, meteorcloudy commented on modules/highwayhash/0.0.0-20240305-5ad3bf8/patches/add_build_file.patch
> ++config_setting(
I think `k8` just means `x86_64` (See [this post](https://stackoverflow.com/questions/59082595/what-does-k8-mean-in-bazel-info-local-cpu-resources-output)), but I don't see `haswell` in https://github.com/bazelbuild/platforms/blob/main/cpu/BUILD, maybe we should add one.

I don't mind checking in this module as it is now, but I think we'll have to migrate at some point to properly support those platforms.

2024-04-15 11:23 UTC, meteorcloudy commented on modules/highwayhash/0.0.0-20240305-5ad3bf8/patches/add_build_file.patch
> ++config_setting(
I'm actually not sure, it seems `haswell` is in fact using `x86_64`, according to https://github.com/bazelbuild/platforms/blob/2af915c086d82ab0b233c8ff420ca72e128b8790/cpu/BUILD#L16-L20, it's probably better to be defined as a local cpu constraint.

2024-04-16 08:41 UTC, meteorcloudy approved these changes

2024-04-16 08:41 UTC, merged