sdl@2.0.8
bazelbuild/bazel-central-registry pull request #1887
Opened 2024-04-25 17:48 UTC by mmorel-35

Release: https://github.com/libsdl-org/SDL/releases/tag/release-2.0.8

Used by:
* https://github.com/google/quic-trace

2024-04-25 17:48 UTC, bazel-io commented
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (sdl) have been updated in this PR. Please review the changes.

2024-04-29 16:49 UTC, zaucy requested changes
I think this setup might be surprising for most when trying to consume this module.

2024-04-29 16:49 UTC, zaucy commented on modules/sdl/2.0.8/patches/add_build_file.patch
> ++    }),
Is there a reason sdl is using system installed SDL2 for linux and being compiled for macos?

2024-04-29 16:49 UTC, zaucy commented on modules/sdl/2.0.8/patches/module_dot_bazel.patch
> ++)
probably should add a compatibility number as `2`?

2024-04-29 16:49 UTC, zaucy commented on modules/sdl/2.0.8/presubmit.yml
> +    - '--cxxopt=-std=c++17'
this would probably be better added in the `copts` of the `cc_library` instead of as a build flag in the presubmit.

2024-04-29 16:49 UTC, zaucy commented on modules/sdl/2.0.8/presubmit.yml
> +  - macos_arm64
ideally Windows is also supported

2024-04-29 21:16 UTC, zaucy commented on modules/sdl/2.0.8/patches/add_build_file.patch
> ++    }),
> I took everything from quic-trace.

Understandable.

I think there's a few sdl2 build files out there. I would like it in the BCR, but I think it should be a little more complete than the one in `quic-trace`. I don't have one off hand, but I have some old ones https://github.com/bazelregistry/sdl2/blob/main/BUILD.bazel that I could maybe combine with the `quic-trace` one to make something more complete. I don't know when I'll be able to do it though.

2024-05-17 07:47 UTC, closed without merging

2024-05-17 15:30 UTC, zaucy commented
hey @mmorel-35 I did some major work to get SDL running with bzlmod if you want to check it out here: https://github.com/zaucy/SDL

Currently it just has Windows support, but I plan to add other platforms as well. If you want to contribute (especially on the macOS side) that would be really helpful. It was quite the challenge to get the SDL config to generate based on bazels config settings, but it seems to be working so far.