Add DLONG support for osqp
bazelbuild/bazel-central-registry pull request #2147
Opened 2024-05-29 16:57 UTC by udaya2899

This PR:
- Adds DLONG flag to build OSQP with 64-bit integers to fix #2135 
- Without this change, google/osqp-cpp cannot build on Bazel, and cannot be published to BCR

The maintainer @wep21 has commented some concerns about DLONG and its relation with `qdldl` too. Please let me know what else I can do to enable this.

2024-05-29 16:57 UTC, bazel-io commented
Hello @wep21, modules you maintain (osqp) have been updated in this PR. Please review the changes.

2024-05-29 17:07 UTC, mering requested changes
Do not change existing versions. Move your changes to version `0.6.3.bcr.1`.

2024-05-29 17:22 UTC, udaya2899 commented
> Do not change existing versions. Move your changes to version `0.6.3.bcr.1`.

Sorry. Changed now.

2024-06-03 23:50 UTC, wep21 commented
@udaya2899 Could you also change float type in qdldl to match the one in osqp?

2024-06-04 13:04 UTC, bazel-io commented
Hello @wep21, modules you maintain (osqp, qdldl) have been updated in this PR. Please review the changes.

2024-06-04 13:28 UTC, mering reviewed
Please also update the PR title and description to include qdldl.

2024-06-04 13:28 UTC, mering commented on modules/qdldl/0.1.7.bcr.1/patches/add_build_file.patch
> ++        # Keep the `int` type sync'd with the build of @osqp_internal and
```suggestion
+        # Keep the `float` type sync'd with the build of @osqp_internal and
```

2024-06-04 13:28 UTC, mering commented on modules/qdldl/0.1.7.bcr.1/source.json
> +        "add_cmake_configure_file.patch": "sha256-qge+NoLlQcrPkS5AR0TbJKkhE3FETgjuzvj9O0WqWwc=",
FYI: If this file didn't change, you can reference this via `../../0.1.7/patches/X.patch`.

2024-06-04 16:36 UTC, udaya2899 commented
Requesting @bazelbuild/bcr-maintainers to add the skip github link check as both osqp/osqp and osqp/qldl have only tags but not releases per [this blog](https://blog.bazel.build/2023/02/15/github-archive-checksum.html)

2024-06-04 17:42 UTC, udaya2899 commented
@wep21 The PR is ready for review again. Can you check?

2024-06-06 09:11 UTC, udaya2899 commented
@wep21 friendly ping. This will help me unblock #2134. Can you please review?

2024-06-06 21:27 UTC, wep21 approved these changes
LGTM. Thanks.

2024-06-06 21:39 UTC, bazel-io approved these changes
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

2024-06-07 01:29 UTC, merged