BCR contribution policy
bazelbuild/bazel-central-registry pull request #252
Opened 2022-11-02 13:32 UTC by radvani13

Adding a BCR contribution policy

2022-11-02 13:34 UTC, meteorcloudy commented
/cc @philomathing

2022-11-02 13:50 UTC, brentleyjones reviewed
Just some Markdown formatting suggestions, to better match the spec.

2022-11-02 13:50 UTC, brentleyjones commented on docs/bcr-contribution-guide.md
> +
```suggestion
```

2022-11-02 13:50 UTC, brentleyjones commented on docs/bcr-contribution-guide.md
> +Contributors should follow these policies when reviewing and accepting modules to the Bazel Central Registry:
```suggestion
# Bazel Central Registry (BCR) contribution policy contribution policies

Contributors should follow these policies when reviewing and accepting modules to the Bazel Central Registry:
```

2022-11-02 13:50 UTC, brentleyjones commented on docs/bcr-contribution-guide.md
> +Registry maintainers and module maintainers maintain the BCR. BCR maintainers are members of the community who have restricted ability to accept Bazel-built reusable packages into the BCR.
```suggestion
## BCR maintenance policies

Registry maintainers and module maintainers maintain the BCR. BCR maintainers are members of the community who have restricted ability to accept Bazel-built reusable packages into the BCR.
```

2022-11-02 13:50 UTC, brentleyjones commented on docs/bcr-contribution-guide.md
> +- Review and accept contributions made by the community that align with the BCR contribution policy. Maintainers can merge any PR they have carefully reviewed and is passing CI. BCR maintainer review
```suggestion
### Responsibilities of a BCR maintainer

- Review and accept contributions made by the community that align with the BCR contribution policy. Maintainers can merge any PR they have carefully reviewed and is passing CI. BCR maintainer review is required when:
```

2022-11-02 13:50 UTC, brentleyjones commented on docs/bcr-contribution-guide.md
> +Every module must have a list of maintainers provided in its metadata.json file. The first contributor to a Bazel module is likely be appointed as the module maintainer. Anyone can apply to be a main
```suggestion
## Become a module maintainer

Every module must have a list of maintainers provided in its metadata.json file. The first contributor to a Bazel module is likely be appointed as the module maintainer. Anyone can apply to be a maintainer of some specific modules. Library authors / rule authors / Bazel users who have special interest on some projects can be module maintainers.
```

2022-11-02 13:50 UTC, brentleyjones commented on docs/bcr-contribution-guide.md
> +Whenever possible, conduct all communication in public on GitHub. Contact maintainers via GitHub or Slack. Contact maintainers over slack group [bzlmod](https://bazelbuild.slack.com/archives/C014RARE
```suggestion
## Contacting the repository or module maintainers

Whenever possible, conduct all communication in public on GitHub. Contact maintainers via GitHub or Slack. Contact maintainers over slack group [bzlmod](https://bazelbuild.slack.com/archives/C014RARENH0) when contacting over GiHub is not possible.
```

2022-11-02 13:50 UTC, brentleyjones commented on docs/bcr-contribution-guide.md
> +Maintainers are community-driven volunteers. Hence, most PRs may be addressed in 3 business days. If a PR is not marked with a label "awaiting user response", then it should be addressed by a registe
```suggestion
### Maintenance timeline expectations

Maintainers are community-driven volunteers. Hence, most PRs may be addressed in 3 business days. If a PR is not marked with a label "awaiting user response", then it should be addressed by a register maintainer within 3 days.
```

2022-11-02 13:50 UTC, brentleyjones commented on docs/bcr-contribution-guide.md
> +-   BCR modules can only depend on modules already in the BCR.
```suggestion
- All changes to the BCR repository must be submitted and reviewed as a pull request.
- Add-only: existing module versions must not be modified to ensure reproducible builds.
- Every module version must have a [presubmit.yml](https://docs.google.com/document/d/1moQfNcEIttsk6vYanNKIy3ZuK53hQUFq1b1r0rmsYVg/edit#heading=h.e6t527rxhw5i) file.
-   BCR modules can only depend on modules already in the BCR.
```

2022-11-02 13:50 UTC, brentleyjones commented on docs/bcr-contribution-guide.md
> +### Responsibilities of a module maintainer
```suggestion
### Responsibilities of a module maintainer

```

2022-11-02 13:50 UTC, brentleyjones commented on docs/bcr-contribution-guide.md
> +-   Update new versions for the designated Bazel module.
```suggestion
- Review and approve changes related to the designated Bazel module.
- Update new versions for the designated Bazel module.
```

2022-11-03 03:16 UTC, alexeagle approved these changes

2022-11-03 13:25 UTC, fmeum approved these changes

2022-11-03 13:38 UTC, meteorcloudy requested changes

2022-11-03 16:26 UTC, radvani13 commented
Hi All, I think I've got everything, but I am not very good with git - so please let me know

2022-11-04 14:28 UTC, meteorcloudy approved these changes

2022-11-04 14:28 UTC, merged