Add googletest@1.15.2
bazelbuild/bazel-central-registry pull request #2520
Opened 2024-07-31 13:46 UTC by derekmauro

2024-07-31 14:01 UTC, derekmauro commented
Is the CI check written in a way that it does not handle `dev_dependency = True`?

2024-07-31 22:29 UTC, Wyverald commented
Indeed -- BCR CI is supposed to spot check your module from the viewpoint of a user (aka dependent). They don't see your dev deps.

2024-07-31 22:29 UTC, Wyverald approved these changes

2024-07-31 22:29 UTC, merged

2024-11-22 17:27 UTC, Mrzosef requested changes

2024-11-22 17:27 UTC, Mrzosef commented on modules/googletest/1.15.2/presubmit.yml
> +  - 7.x
-

2024-11-22 17:27 UTC, Mrzosef commented on modules/googletest/metadata.json
> -    "1.15.0"
-

2024-11-22 17:27 UTC, Mrzosef commented on modules/googletest/metadata.json
> -    "1.15.0"
_