Add Lcov
bazelbuild/bazel-central-registry pull request #2637
Opened 2024-08-18 09:23 UTC by lalten

Depends on https://github.com/bazelbuild/bazel-central-registry/pull/2631 and https://github.com/bazelbuild/bazel-central-registry/pull/2636

2024-08-18 09:23 UTC, bazel-io commented
Hello @mortenmj, modules you maintain (rules_perl) have been updated in this PR. Please review the changes.

2024-08-18 09:23 UTC, bazel-io commented
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (lcov, rules_cpan) have been updated in this PR. Please review the changes.

2024-08-20 09:01 UTC, bazel-io commented
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (lcov) have been updated in this PR. Please review the changes.

2024-08-20 09:10 UTC, meteorcloudy requested changes

2024-08-20 09:10 UTC, meteorcloudy commented on modules/lcov/metadata.json
> +    "repository": [],
Please add the source repo here.

2024-08-20 09:18 UTC, lalten commented on modules/lcov/metadata.json
> +    "repository": [],
oops! fixed

2024-08-20 09:27 UTC, meteorcloudy commented
Hmm, those files are essentially fetched by 
https://cs.opensource.google/bazel/bazel/+/master:tools/build_defs/repo/utils.bzl;l=106-114, which doesn't set the executable bit. I don't think we can even get this information at this point? /cc @fzakaria @Wyverald

2024-08-20 10:02 UTC, lalten commented
Generating the .sh with `genrule(..., executable=True)` now.
I now wonder if it would also have worked to keep the overlay file but then patch the permission bits with a patch file?

2024-08-20 12:05 UTC, meteorcloudy commented
> I now wonder if it would also have worked to keep the overlay file but then patch the permission bits with a patch file?

Yes, I think that's possible:
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/repository/PatchUtil.java;l=459-468

2024-08-22 08:21 UTC, meteorcloudy approved these changes
Thanks!

2024-08-22 08:22 UTC, merged