feat: add boost process
bazelbuild/bazel-central-registry pull request #3074
Opened 2024-10-30 17:02 UTC by wep21

- as title
- need skip url stability check
- parse headers

2024-10-30 17:02 UTC, bazel-io commented
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (boost.process) have been updated in this PR. Please review the changes.

2024-10-30 17:06 UTC, Vertexwahn submitted a review, later dismissed

2024-10-30 17:15 UTC, Vertexwahn commented
@wep21 Sorry, I have unfortunately overlooked this - maybe we create a bcr1 out of this?

2024-10-30 17:17 UTC, Vertexwahn commented on modules/boost.process/1.83.0/MODULE.bazel
> +    version = "1.83.0",
Change to bcr1

2024-10-30 17:17 UTC, Vertexwahn requested changes

2024-10-30 17:17 UTC, Vertexwahn commented on modules/boost.process/metadata.json
> +        }
Add

        {
            "github": "hofbi",
            "name": "Markus Hofbauer"
        }

2024-10-30 17:22 UTC, bazel-io commented
Hello @Vertexwahn, @hofbi, modules you maintain (boost.process) have been updated in this PR. Please review the changes.

2024-10-30 17:24 UTC, wep21 commented on modules/boost.process/metadata.json
> +        }
rebased from main

2024-10-30 17:24 UTC, Vertexwahn approved these changes

2024-10-30 17:24 UTC, wep21 commented on modules/boost.process/1.83.0/MODULE.bazel
> +    version = "1.83.0",
added new version

2024-10-30 17:40 UTC, bazel-io submitted a review, later dismissed
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

2024-10-30 20:02 UTC, Vertexwahn approved these changes

2024-10-31 09:53 UTC, meteorcloudy approved these changes

2024-10-31 10:04 UTC, meteorcloudy commented
Please fix the incompatibility with Bazel rolling

2024-10-31 11:02 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.concept_check, boost.process) have been updated in this PR. Please review the changes.

2024-10-31 11:02 UTC, bazel-io commented
Hello @hofbi, modules you maintain (boost.process) have been updated in this PR. Please review the changes.

2024-10-31 11:25 UTC, Vertexwahn submitted a review, later dismissed

2024-10-31 11:34 UTC, bazel-io approved these changes
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

2024-10-31 12:32 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.concept_check, boost.process, boost.smart_ptr) have been updated in this PR. Please review the changes.

2024-10-31 12:43 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.concept_check, boost.conversion, boost.process, boost.smart_ptr) have been updated in this PR. Please review the changes.

2024-10-31 12:55 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.concept_check, boost.conversion, boost.optional, boost.process, boost.smart_ptr) have been updated in this PR. Please review the changes.

2024-10-31 13:05 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.concept_check, boost.conversion, boost.fusion, boost.optional, boost.process, boost.smart_ptr) have been updated in this PR. Please review the changes.

2024-10-31 13:30 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.concept_check, boost.conversion, boost.fusion, boost.iterator, boost.optional, boost.process, boost.smart_ptr, boost.tokenizer) have been updated in this PR. Please review the changes.

2024-10-31 13:48 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.concept_check, boost.conversion, boost.fusion, boost.iterator, boost.optional, boost.process, boost.smart_ptr, boost.tokenizer, boost.type_index) have been updated in this PR. Please review the changes.

2024-10-31 13:58 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.concept_check, boost.conversion, boost.fusion, boost.iterator, boost.optional, boost.process, boost.smart_ptr, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-10-31 14:04 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.concept_check, boost.conversion, boost.fusion, boost.iterator, boost.optional, boost.process, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-10-31 14:18 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.align, boost.concept_check, boost.conversion, boost.fusion, boost.iterator, boost.optional, boost.process, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-10-31 14:25 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.align, boost.atomic, boost.concept_check, boost.conversion, boost.fusion, boost.iterator, boost.optional, boost.process, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-10-31 14:36 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.align, boost.array, boost.atomic, boost.concept_check, boost.conversion, boost.fusion, boost.iterator, boost.optional, boost.process, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-10-31 15:55 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.align, boost.array, boost.atomic, boost.concept_check, boost.conversion, boost.exception, boost.fusion, boost.integer, boost.iterator, boost.optional, boost.process, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-10-31 16:02 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.align, boost.array, boost.atomic, boost.concept_check, boost.conversion, boost.exception, boost.fusion, boost.integer, boost.iterator, boost.optional, boost.process, boost.regex, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-10-31 16:13 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.align, boost.array, boost.atomic, boost.concept_check, boost.conversion, boost.exception, boost.fusion, boost.integer, boost.iterator, boost.optional, boost.process, boost.range, boost.regex, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-10-31 16:27 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.atomic, boost.concept_check, boost.conversion, boost.exception, boost.fusion, boost.integer, boost.iterator, boost.optional, boost.process, boost.range, boost.regex, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-10-31 16:37 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.atomic, boost.concept_check, boost.conversion, boost.detail, boost.exception, boost.fusion, boost.integer, boost.iterator, boost.optional, boost.process, boost.range, boost.regex, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-10-31 16:58 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.atomic, boost.concept_check, boost.conversion, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.optional, boost.pool, boost.process, boost.range, boost.regex, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-10-31 17:04 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.atomic, boost.concept_check, boost.context, boost.conversion, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.optional, boost.pool, boost.process, boost.range, boost.regex, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-10-31 17:37 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.atomic, boost.concept_check, boost.context, boost.conversion, boost.coroutine, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.regex, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-10-31 18:16 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.atomic, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.regex, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-10-31 19:02 UTC, Vertexwahn submitted a review, later dismissed

2024-10-31 19:18 UTC, bazel-io submitted a review, later dismissed
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

2024-11-01 01:23 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.atomic, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.regex, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 01:29 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.atomic, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.regex, boost.smart_ptr, boost.system, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 01:48 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.atomic, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.regex, boost.smart_ptr, boost.system, boost.test, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 01:58 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.atomic, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.lexical_cast, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.regex, boost.smart_ptr, boost.system, boost.test, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 02:11 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.atomic, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.date_time, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.lexical_cast, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.regex, boost.smart_ptr, boost.system, boost.test, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 02:40 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.atomic, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.date_time, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.lexical_cast, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.rational, boost.regex, boost.smart_ptr, boost.system, boost.test, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 02:46 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.atomic, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.date_time, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.lexical_cast, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.ratio, boost.rational, boost.regex, boost.smart_ptr, boost.system, boost.test, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 03:14 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.atomic, boost.chrono, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.date_time, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.lexical_cast, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.ratio, boost.rational, boost.regex, boost.smart_ptr, boost.system, boost.test, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 03:54 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.asio, boost.atomic, boost.chrono, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.date_time, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.lexical_cast, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.ratio, boost.rational, boost.regex, boost.smart_ptr, boost.system, boost.test, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 03:59 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.asio, boost.atomic, boost.chrono, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.date_time, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.lexical_cast, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.ratio, boost.rational, boost.regex, boost.smart_ptr, boost.system, boost.test, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 04:02 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.asio, boost.atomic, boost.chrono, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.date_time, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.lexical_cast, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.ratio, boost.rational, boost.regex, boost.smart_ptr, boost.system, boost.test, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 05:16 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.asio, boost.atomic, boost.chrono, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.date_time, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.lexical_cast, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.ratio, boost.rational, boost.regex, boost.smart_ptr, boost.system, boost.test, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 05:30 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.asio, boost.atomic, boost.chrono, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.date_time, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.lexical_cast, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.ratio, boost.rational, boost.regex, boost.smart_ptr, boost.system, boost.test, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 06:30 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.asio, boost.atomic, boost.chrono, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.date_time, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.lexical_cast, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.ratio, boost.rational, boost.regex, boost.smart_ptr, boost.system, boost.test, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 06:43 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.asio, boost.atomic, boost.chrono, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.date_time, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.lexical_cast, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.ratio, boost.rational, boost.regex, boost.smart_ptr, boost.system, boost.test, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 07:12 UTC, bazel-io commented
Hello @Vertexwahn, modules you maintain (boost.algorithm, boost.align, boost.array, boost.asio, boost.atomic, boost.chrono, boost.concept_check, boost.container, boost.context, boost.conversion, boost.coroutine, boost.date_time, boost.detail, boost.exception, boost.filesystem, boost.fusion, boost.integer, boost.iterator, boost.lexical_cast, boost.numeric_conversion, boost.optional, boost.pool, boost.process, boost.range, boost.ratio, boost.rational, boost.regex, boost.smart_ptr, boost.system, boost.test, boost.tokenizer, boost.type_index, boost.variant2) have been updated in this PR. Please review the changes.

2024-11-01 07:27 UTC, wep21 commented
@meteorcloudy tests seem to be flaky. Could you rerun ci again?

2024-11-01 07:31 UTC, Vertexwahn approved these changes

2024-11-01 07:39 UTC, bazel-io approved these changes
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

2024-11-01 07:39 UTC, merged

2024-11-01 07:42 UTC, fmeum commented
What a PR! I merged it, but want to point out that there are a bunch of `#pragma once in main file` warnings in the log. Maybe `parse_headers` isn't set up quite right?