Add openssl 3.3.1.bcr.1
bazelbuild/bazel-central-registry pull request #3397
Opened 2024-12-11 17:56 UTC by illicitonion

2024-12-11 17:56 UTC, bazel-io commented
Hello @raccoons-build, modules you maintain (openssl) have been updated in this PR. Please review the changes.

2024-12-12 08:04 UTC, fmeum requested changes

2024-12-12 08:04 UTC, fmeum commented on modules/openssl/3.3.1.bcr.1/MODULE.bazel
> +    compatibility_level = 3,
Unfortunately, this means that now this version and the previous one will be considered incompatible. Sorry for the back and forth, but I would recommend sticking to the level value you constructed for the first version and leaving a comment on it to explain how it's supposed to be kept constant at least for all minor and patch versions

2024-12-12 08:29 UTC, closed without merging

2024-12-12 09:03 UTC, illicitonion commented
Hopefully the last re-PR: https://github.com/bazelbuild/bazel-central-registry/pull/3400 :)