spdlog@1.15.0.bcr.2
bazelbuild/bazel-central-registry pull request #3425
Opened 2024-12-15 16:06 UTC by jwnimmer-tri

Compared to `1.15.0.bcr.1`, add a `bool_flag` for header_only mode.
This enables `--@spdlog//:header_only=False` on the bazel command line.

---

See also #1769 which requests a mechanism to enable `USE_STD_FORMAT`.  If desirable, I could try adding that option as an additional flag in this pull request.

2024-12-15 16:07 UTC, bazel-io commented
Hello @Vertexwahn, @c8ef, modules you maintain (spdlog) have been updated in this PR. Please review the changes.

2024-12-15 16:08 UTC, jwnimmer-tri commented
@bazel-io skip_check unstable_url

2024-12-15 18:17 UTC, Vertexwahn requested changes

2024-12-15 18:17 UTC, Vertexwahn commented on modules/spdlog/1.15.0.bcr.2/MODULE.bazel
> +    compatibility_level = 1,
Add `bazel_compatibility = [">=7.2.1"],` since you depend on overlay feature from Bazel

2024-12-15 18:17 UTC, Vertexwahn commented on modules/spdlog/1.15.0.bcr.2/presubmit.yml
> +  bazel: [7.x, rolling]
You can change this to `bazel: [7.x, 8.x, rolling]`

2024-12-15 18:22 UTC, Vertexwahn commented
Can we test also the` --@spdlog//:header_only=False` variant in CI?
`USE_STD_FORMAT` as a flag would also be nice - but we can defer this to a later PR...

2024-12-15 19:09 UTC, jwnimmer-tri commented
Good idea; test added.

2024-12-15 19:23 UTC, Vertexwahn submitted a review, later dismissed

2024-12-15 19:39 UTC, bazel-io approved these changes, later dismissed
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

2024-12-16 01:11 UTC, c8ef submitted a review, later dismissed

2024-12-16 23:35 UTC, jwnimmer-tri commented
The new presubmit matrix was failing on windows with UTF-8 complaints.  I added `--cxxopt=/utf-8` to fix it, similar to the existing pattern for `fmt`.

2024-12-17 00:41 UTC, Vertexwahn approved these changes

2024-12-17 01:59 UTC, bazel-io approved these changes
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

2024-12-17 07:34 UTC, merged